src/davesite/lsyslegacy/blueprint.py
'''
Created on Sept 30, 2013

Legacy LSystem code.  THis code started off as me hacking around one afternoon and it shows.  This code will be updated for security and massive usability 
issues only.  A re-write is planned but there is no timeline.  However, it provides enough functionality to be worth displaying.

Input is taken from the client and handed to the handlerlib where the LSystem is expanded to the desired iteration and drawn using PIL.  Timeouts in the 
drawing handler exist to prevent excessive memory usage. 

The image is base64 encoded and returned to the user along with the list of messages.  Otherwise, the image would have to be cached where it could be loaded
from the client dynamically.  

@author: david
'''
import base64

import davesite.lsyslegacy.handlerlib as handlerlib
from davesite.app.common import inject_header_link

from flask import Blueprint, render_template, request


lsyslegacy = Blueprint('lsyslegacy', __name__,
                        template_folder='templates',
                        static_folder = 'static')
inject_header_link(lsyslegacy)


######################
#Index
######################

examples = dict(empty  = dict(start='', productions='', angle=90, step=5, iterations=5),
                dragon = dict(start='FX', productions = "X=X+YF\nY=FX-Y", angle=90, step=10, iterations=5),
                plant  = dict(start='++X', productions = "X=F-[[X]+X]+F[+FX]-X\nF=FF", angle=25, step=10, iterations=3),
                plant2 = dict(start='++++F', productions = "F=CGFF-[CN-F+F+F]+[CG+F-F-F]", angle=22, step=10, iterations=3),
                sierpinski = dict(start='A', productions='A=B-A-B\nB=A+B+A', angle=60, step=5, iterations=5),
                koch = dict(start='F', productions='F=F+F-F-F+F', angle=90, step=5, iterations=3),
                snowflake = dict(start='F--F--F', productions="F=F+F--F+F", angle=60, step=5, iterations=3),)


@lsyslegacy.route('/')
def index():
    """
    Overview: Renders the main user interface and pre-populate it with the given example
    Returns:  Main GUI HTML
    """
    
    example = examples.get(request.args.get('example'), examples['empty'])
    return render_template('lsyslegacy/index.html', values = example)

#########################
#handler
#########################

@lsyslegacy.route('/handler')
def handler():
    """
    Overview: Handles. validates and returns the image or a list of problems encountered and ways to avoid them.
    Returns: HTML document with base64 encoded image and server messages in a list.
    """

    validated_keys, messages = handlerlib.parse_form_input(request)
    img_data = None
    if len(messages) == 0: #do not try to do anything if we got parse errors
        img_data, draw_messages = handlerlib.get_lsystem_drawing(validated_keys["start"], 
                                                                 validated_keys["productions"], 
                                                                 validated_keys["angle"], 
                                                                 validated_keys["step"], 
                                                                 validated_keys["iterations"])
        messages.extend(draw_messages)


    if img_data is not None:
        img_data = base64.encodestring(img_data)
    else:
        img_data = ''   
    return render_template('lsyslegacy/image.html', messages = messages, img = img_data)
    

src/davesite/lsyslegacy/templates/lsyslegacy/image.html
<html>
        <head></head>
        <body onload="parent.frame_resize();">
        
            {% if messages|length > 0 %}
				<h4>The following messages were generated by the system while handling your request:</h4>
	        	<ul>
	        	{% for message in messages %}
				    <li>{{ message }}</li>
				{% endfor %}
	        	</ul>  

			{% endif %}  
            
            {% if img %}
			<img src='data:image/png;base64,{{img}}' />
			{% endif %}
                                       
        </body>
</html>

src/davesite/lsyslegacy/templates/lsyslegacy/index.html
{% extends "layout.html" %}
{% block title %}Legacy L-System{% endblock title %}

{% block head %}
	<style type="text/css">
	          table{
	          	border-collapse:collapse;
          	  }
	          table, th, td{
	          	border: 1px solid black;
          	  }
	          input[type="number"]{
	          	width:3em;
	          }
	          textarea, input{
	          	width: 20em;
	          }
	          iframe{
	          	border:0;
	          	overflow:hidden;
	          	/*height:300em;*/
	          	width:100%;
	          }

	</style>
	
	<script type="text/javascript">
	
		function frame_resize(){
			$('#lsys_frame').contents().find('body').css({"min-height": "100", "overflow" : "hidden"});
			$('#lsys_frame').height($('#lsys_frame').contents().find('body').height() + 20);	
		}

	</script>
	
{% endblock head %}

{% block body %}
		<h4>L-System Parser</h4>
		<p>
            Welcome to a simple <a href="http://en.wikipedia.org/wiki/L-system">L-System</a> parser.  Consult the following table for valid production symbols.
	    <p>
	
	<div>
	
    	<div style="float:left;">
            <form method='get' target='_viewer' action="{{ url_for('lsyslegacy.handler') }}">
            
                <label for="start"> start: </label> <br />
                <input type="text" name="start" id="start" value="{{values['start']}}" />
                    
                <br />
            
                <label for="productions"> productions: </label> <br />
                <textarea name="productions" id="productions" rows="5" cols="30">{{values['productions']}}</textarea>
            
                <br />
            
                <div style="float:left;">
                    <label for="angle"> angle: </label> <br />
                    <input type="number" name="angle" id="iterations" min="0" max="360" value="{{values['angle']}}" />
                </div>
                <div style="float:left;padding-left:1em;">
                    <label for="step"> step: </label> <br />
                    <input type="number" name="step" id="step" min="0" max="50" value="{{values['step']}}" />
                </div>
                <div style="float:left;padding-left:1em;">
                    <label for="iterations"> iterations: </label> <br />
                    <input type="number" name="iterations" id="iterations" min="0" max="20" value="{{values['iterations']}}" />
                </div>
            
                <br style='clear:both' />
            
                <input type='submit' value='Submit' class='btn' />
            	<input type='button' value='Force Resize' class='btn' onclick="frame_resize();" />
            
            </form>
	    </div>
	
    	<table style='float:left;margin-left:3em;'>
    		<thead>
    			<tr>
    				<TH>INSTRUCTION</TH>
    				<TH>SYMBOL</TH>
    			</tr>		
    		</thead>
    		<tbody>
    			<tr>
    				<td>Draw forward </td>
    				<td>a, b, f </td>
    			</tr>
    			<tr>
    				<td>Move forward</td>
    				<td>m</td>
    			</tr>			
    			<tr>
    				<td>Left </td>
    				<td>+ </td>
    			</tr>
    			<tr>
    				<td>Right</td>
    				<td>-</td>
    			</tr>
    			<tr>
    				<td>Push/Pop</td>
    				<td>[/]</td>
    			</tr>
                <tr>
                    <td>Color</td>
                    <td>c#</td>
                </tr>
    			<tr>
    				<td>Place Holders</td>
    				<td>all other letters</td>
    			</tr>
                <tr>
                    <td>Comment Line</td>
                    <td>#</td>
                </tr>
    		</tbody>
    	</table>
            
        <table style='float:left;margin-left:3em;'>
            <thead>
                <tr>
                    <TH>Marker</TH>
                    <TH>Color</TH>
                </tr>        
            </thead>
            <tbody>
                <tr><td>R</td><td style='background-color:red;'>&nbsp;</td></tr>
                <tr><td>O</td><td style='background-color:orange;'>&nbsp;</td></tr>
                <tr><td>Y</td><td style='background-color:yellow;'>&nbsp;</td></tr>
                <tr><td>G</td><td style='background-color:green;'>&nbsp;</td></tr>
                <tr><td>B</td><td style='background-color:blue;'>&nbsp;</td></tr>
                <tr><td>P</td><td style='background-color:purple;'>&nbsp;</td></tr>
                <tr><td>L</td><td style='background-color:black;'>&nbsp;</td></tr>
                <tr><td>N</td><td style='background-color:brown;'>&nbsp;</td></tr>
            </tbody>
        </table>
        
        <table style='float:left;margin-left:3em;'>
            <thead>
                <tr>
                    <TH>Examples</TH>
                </tr>        
            </thead>
            <tbody>
                <tr><td> <a href="{{url_for('lsyslegacy.index', example='dragon')}}">Dragon Curve</a> </td></tr>
                <tr><td> <a href="{{url_for('lsyslegacy.index', example='plant')}}">Fractal Plant</a> </td></tr>
                <tr><td> <a href="{{url_for('lsyslegacy.index', example='plant2')}}">Alternate Plant</a> </td></tr>
                <tr><td> <a href="{{url_for('lsyslegacy.index', example='sierpinski')}}">Sierpinski</a> </td></tr>
                <tr><td> <a href="{{url_for('lsyslegacy.index', example='koch')}}">Koch</a> </td></tr>
                <tr><td> <a href="{{url_for('lsyslegacy.index', example='snowflake')}}">Snowflake</a> </td></tr>
            </tbody>
        </table>
        
    </div>

        <p style='clear:both' />

        <iframe id = "lsys_frame" name="_viewer" scrolling="no"></iframe>


{% endblock body %}


{% block body_scripts %}
{% endblock body_scripts %}